spring:
  profiles:
    active: dev  # Active le profil de développement, change la configuration en fonction de ce profil

  servlet:
    multipart:
      max-file-size: 50MB  # Limite de taille pour les fichiers uploadés

server:
  servlet:
    context-path: /api/v1/  # Préfixe commun pour toutes les routes de l'application

springdoc:
  default-produces-media-type: application/json  # Définit le type de média par défaut pour la documentation Swagger
